"""
generate_report.py
Generates the Sentio critical academic report as a formatted .docx file.

Screenshots expected in docs/screenshots/:
  01_config_screen.png       — Configure Session screen
  02_device_settings.png     — Device Settings popup
  03_calibration_screen.png  — Calibration / Connecting screen
  04_signal_lost.png         — Signal Lost modal
  05_monitoring_screen.png   — Live Monitoring dashboard
  architecture.png           — Generated by generate_architecture_diagram.py

Run:
  python generate_architecture_diagram.py   # first time
  python generate_report.py
"""

from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import os

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE        = os.path.dirname(__file__)
SHOTS_DIR   = os.path.join(BASE, "docs", "screenshots")
OUT_DIR     = os.path.join(BASE, "docs")
OUT_FILE    = os.path.join(OUT_DIR, "sentio_critical_report.docx")
os.makedirs(SHOTS_DIR, exist_ok=True)
os.makedirs(OUT_DIR, exist_ok=True)

SCREENSHOTS = [
    ("01_config_screen.png",      "Figure 1 — Configuration screen: pattern type selection and signal sensitivity slider."),
    ("02_device_settings.png",    "Figure 2 — Device Settings panel: backend API URL and Muse 2 MAC address configuration."),
    ("03_calibration_screen.png", "Figure 3 — Calibration screen: animated Muse 2 connection sequence with progress indicator."),
    ("04_signal_lost.png",        "Figure 4 — Signal Lost modal: graceful disconnect handling with numbered recovery steps."),
    ("05_monitoring_screen.png",  "Figure 5 — Live Monitoring dashboard: emotion orb, real-time EEG band power chart, visual parameters panel."),
]

# ── Helpers ───────────────────────────────────────────────────────────────────

def set_font(run, name="Times New Roman", size=12, bold=False,
             italic=False, color=None):
    run.font.name   = name
    run.font.size   = Pt(size)
    run.font.bold   = bold
    run.font.italic = italic
    if color:
        run.font.color.rgb = RGBColor(*color)

def add_heading(doc, text, level=1):
    p = doc.add_paragraph()
    p.paragraph_format.space_before    = Pt(14)
    p.paragraph_format.space_after     = Pt(4)
    p.paragraph_format.keep_with_next  = True
    run = p.add_run(text)
    if level == 0:
        set_font(run, size=18, bold=True)
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.paragraph_format.space_before = Pt(0)
        p.paragraph_format.space_after  = Pt(6)
    elif level == 1:
        set_font(run, size=13, bold=True)
        p.paragraph_format.space_before = Pt(18)
    elif level == 2:
        set_font(run, size=12, bold=True)
        p.paragraph_format.space_before = Pt(10)
    return p

def add_body(doc, text, indent=False, space_after=8):
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(space_after)
    if indent:
        p.paragraph_format.left_indent = Cm(0.8)
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    run = p.add_run(text)
    set_font(run)
    return p

def add_mixed(doc, parts, indent=False, space_after=8):
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(space_after)
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    if indent:
        p.paragraph_format.left_indent = Cm(0.8)
    for text, bold, italic in parts:
        run = p.add_run(text)
        set_font(run, bold=bold, italic=italic)
    return p

def add_separator(doc):
    p = doc.add_paragraph()
    p.paragraph_format.space_after  = Pt(2)
    p.paragraph_format.space_before = Pt(2)
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '6')
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), 'AAAAAA')
    pBdr.append(bottom)
    pPr.append(pBdr)

def add_ref(doc, text):
    p = doc.add_paragraph()
    p.paragraph_format.left_indent        = Cm(1.0)
    p.paragraph_format.first_line_indent  = Cm(-1.0)
    p.paragraph_format.space_after        = Pt(4)
    run = p.add_run(text)
    set_font(run, size=11)
    return p

def add_image(doc, filename, caption, width=Inches(5.8)):
    """Insert an image centred with a caption below it, if the file exists."""
    path = os.path.join(SHOTS_DIR, filename)
    if not os.path.exists(path):
        # Insert a grey placeholder paragraph instead
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.paragraph_format.space_before = Pt(8)
        p.paragraph_format.space_after  = Pt(4)
        run = p.add_run(f"[Image not found: {filename}]")
        set_font(run, size=10, italic=True, color=(160, 160, 160))
    else:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.paragraph_format.space_before = Pt(12)
        p.paragraph_format.space_after  = Pt(4)
        run = p.add_run()
        run.add_picture(path, width=width)

    # Caption
    cap = doc.add_paragraph()
    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    cap.paragraph_format.space_after  = Pt(14)
    cap.paragraph_format.space_before = Pt(2)
    cap_run = cap.add_run(caption)
    set_font(cap_run, size=9, italic=True, color=(100, 100, 100))
    return cap

# ── Document ──────────────────────────────────────────────────────────────────
doc = Document()

for section in doc.sections:
    section.top_margin    = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin   = Cm(3.0)
    section.right_margin  = Cm(2.5)

# ── Title ─────────────────────────────────────────────────────────────────────
add_heading(doc,
    "Sentio: A Critical Evaluation of an EEG-Driven Wearable LED System",
    level=0)

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
p.paragraph_format.space_after = Pt(2)
r = p.add_run("Critical Academic Report")
set_font(r, size=11, italic=True, color=(100, 100, 100))

p2 = doc.add_paragraph()
p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
p2.paragraph_format.space_after = Pt(20)
r2 = p2.add_run("Sentio Project  |  WS2812B Arduino Version  |  2026")
set_font(r2, size=10, color=(130, 130, 130))

add_separator(doc)

# ── Architecture Diagram ──────────────────────────────────────────────────────
add_heading(doc, "System Architecture", level=1)
add_image(doc, "architecture.png",
          "Figure 0 — Sentio system architecture: Muse 2 headband to WS2812B LED "
          "matrix via ESP32 WebSocket, with React monitoring dashboard as secondary output.",
          width=Inches(6.0))

add_separator(doc)

# ── 1. Introduction ───────────────────────────────────────────────────────────
add_heading(doc, "1. Introduction")

add_body(doc,
    "Sentio is an emotion-driven wearable interactive system that translates "
    "real-time electroencephalography (EEG) data into generative visual patterns "
    "rendered on a 16x16 WS2812B LED matrix embedded in a t-shirt. A Muse 2 "
    "headband captures brainwave activity; a Python backend classifies five "
    "emotional states -- calm, focused, stressed, relaxed, and excited -- and "
    "streams results wirelessly via WebSocket to an ESP32 microcontroller, which "
    "drives 256 individually addressable LEDs through four distinct visual patterns: "
    "Ondas Fluidas, Padrao Geometrico, Pulsos Ritmicos, and Estrelas e Particulas. "
    "The system also provides a React web dashboard (Figure 5) for real-time "
    "monitoring by operators. This report critically evaluates Sentio's "
    "effectiveness as an interactive system, examining usability, interaction "
    "design principles, and system-level thinking to assess how successfully it "
    "bridges complex neurological data and a meaningful wearable experience.")

# Insert config screen after introduction
add_image(doc, "01_config_screen.png", SCREENSHOTS[0][1])

# ── 2. Usability and Interaction Analysis ─────────────────────────────────────
add_heading(doc, "2. Usability and Interaction Analysis")

add_mixed(doc, [
    ("Effectiveness.  ", True, False),
    ("Sentio achieves its primary goal through a clearly defined five-stage "
     "pipeline: session configuration, device connection, calibration, real-time "
     "monitoring, and LED pattern output (Figures 1-3). The configuration screen "
     "(Figure 1) presents pattern type as a 2x2 card grid with inline SVG previews, "
     "reducing the abstraction gap between label and output. This design decision "
     "supports task completion by providing ", False, False),
    ("recognition over recall", False, True),
    (" (Nielsen, 1994). However, effectiveness is contingent on hardware "
     "reliability: Bluetooth connectivity between the Muse headband and the "
     "processing machine constitutes a single point of failure capable of "
     "preventing task completion entirely.", False, False),
])

add_mixed(doc, [
    ("Efficiency.  ", True, False),
    ("The Device Settings panel (Figure 2) allows operators to configure the "
     "backend API URL and Muse MAC address without redeploying the application -- "
     "a pragmatic field-deployment affordance. Calibration (Figure 3) completes "
     "automatically, requiring no active user input. However, efficiency is "
     "undermined by the calibration stage's opacity: the animated progress bar "
     "runs independently of actual backend processing, meaning users cannot "
     "distinguish genuine device communication from a cosmetic animation. This "
     "violates Nielsen's ", False, False),
    ("visibility of system status", False, True),
    (" heuristic and erodes trust with technically literate users.", False, False),
])

# Insert device settings image
add_image(doc, "02_device_settings.png", SCREENSHOTS[1][1])
add_image(doc, "03_calibration_screen.png", SCREENSHOTS[2][1])

add_mixed(doc, [
    ("Satisfaction.  ", True, False),
    ("The wearable form factor creates a compelling experiential proposition. "
     "The four patterns are perceptually differentiated by hue, morphology, and "
     "animation speed, enabling casual observers to detect emotional transitions. "
     "A notable weakness, however, is the absence of secondary feedback channels "
     "(haptic or auditory), and the wearer cannot observe their own chest panel "
     "-- creating an inherent observer-wearer asymmetry that limits personal "
     "experiential depth.", False, False),
])

add_mixed(doc, [
    ("Interaction Principles.  ", True, False),
    ("The Signal Lost modal (Figure 4) demonstrates considered error recovery "
     "design: it presents a numbered three-step recovery checklist with specific "
     "commands (", False, False),
    ("uvicorn main:app", False, False),
    ("), an auto-retry countdown, and a dismiss option. This aligns with "
     "Nielsen's heuristics of ", False, False),
    ("help users recognise, diagnose, and recover from errors", False, True),
    (". The real-time WebSocket stream modulates LED brightness via "
     "signal_quality (0-100), coupling input confidence to output intensity. "
     "However, pattern transitions are instantaneous on emotion change. The "
     "absence of crossfade between states violates continuity principles and "
     "produces jarring visual discontinuities that undermine organic emotional "
     "narrative.", False, False),
])

# Insert signal lost image
add_image(doc, "04_signal_lost.png", SCREENSHOTS[3][1])

# ── 3. System Thinking Perspective ────────────────────────────────────────────
add_heading(doc, "3. System Thinking Perspective")

add_mixed(doc, [
    ("Activity Theory.  ", True, False),
    ("Analysed through Activity Theory (Engestrom, 1987), Sentio situates the "
     "wearer as both ", False, False),
    ("subject", False, True),
    (" and primary data source, employing the EEG-to-LED pipeline as ", False, False),
    ("tool", False, True),
    (" to externalise emotional state as ", False, False),
    ("object", False, True),
    (". This reveals a fundamental tension: the output medium (a chest panel) "
     "is most visible to external observers, not the wearer. This inversion of "
     "the subject-object relationship is unacknowledged in the interface design, "
     "creating an experiential mismatch that limits personal agency.", False, False),
])

add_mixed(doc, [
    ("Cognitive Ergonomics.  ", True, False),
    ("The monitoring dashboard (Figure 5) presents EEG band powers, signal "
     "quality, visual parameters, and a guidance panel simultaneously. From a "
     "cognitive ergonomics perspective (Wickens et al., 2004), this density "
     "serves operator needs but risks overwhelming novice users in exhibition "
     "contexts. The AUTO/MANUAL toggle and band-specific percentage values "
     "(Alpha 9.2%, Beta 23.4%, etc.) demand EEG literacy that cannot be assumed "
     "from a general audience, violating the principle of minimising unnecessary "
     "memory burden.", False, False),
])

add_mixed(doc, [
    ("Distributed Cognition.  ", True, False),
    ("Hutchins' (1995) framework provides the strongest theoretical justification "
     "for Sentio's value: the system externalises an invisible internal state into "
     "a shared, perceptible artefact. However, the five-emotion discrete "
     "classification model imposes a reductive taxonomy onto a continuous "
     "neurological spectrum. The rule-based classifier offers no mechanism for "
     "individual calibration or adaptive learning, and misclassification breaks "
     "the perceived authenticity central to the system's meaning.", False, False),
])

add_mixed(doc, [
    ("System Failure Propagation.  ", True, False),
    ("Bluetooth dropout causes EEG loss -> the backend emits heartbeat-only "
     "frames -> the ESP32 falls back to an idle pattern -> observers perceive the "
     "garment as inactive. The Signal Lost modal (Figure 4) handles this "
     "gracefully at the frontend level, but provides no equivalent notification "
     "on the LED garment itself -- a gap that would be critical in untethered "
     "performance scenarios.", False, False),
])

# Insert monitoring screen
add_image(doc, "05_monitoring_screen.png", SCREENSHOTS[4][1])

# ── 4. Connection to User Research and Heuristics ─────────────────────────────
add_heading(doc, "4. Connection to User Research and Heuristics")

add_body(doc,
    "Sentio targets an exhibition or performance context, implying novice users "
    "with no EEG literacy. The automated calibration and guided sequential flow "
    "align with Nielsen's error prevention heuristic by removing technical "
    "complexity from user control. The emotion-to-pattern mapping applies "
    "established colour-emotion associations -- red/pulse for stress, cyan/wave "
    "for calm (Kaya & Epps, 2004) -- reinforcing intuitive readability without "
    "prior instruction.")

add_body(doc,
    "The monitoring dashboard (Figure 5) exposes all pipeline data simultaneously: "
    "band powers, signal quality, visual parameters, an AI guidance panel, and a "
    "TouchDesigner status pane. While this transparency satisfies Nielsen's "
    "visibility of system status heuristic for expert operators, the information "
    "density risks cognitive overload for the intended exhibition audience. "
    "Progressive disclosure -- hiding technical metrics unless explicitly "
    "requested -- would better serve this user profile.")

add_body(doc,
    "The manual override mode demonstrates awareness of operator needs in rehearsal "
    "or fault scenarios, supporting Nielsen's heuristic of user control and freedom "
    "(Nielsen, 1994). However, the mode is accessible only through the monitoring "
    "interface, requiring a prior successful session start -- limiting its utility "
    "precisely when hardware failure occurs.")

# ── 5. Conclusion ─────────────────────────────────────────────────────────────
add_heading(doc, "5. Conclusion")

add_body(doc,
    "Sentio demonstrates technical and experiential feasibility in translating "
    "EEG data to a wearable LED display. Its sequential interaction flow, "
    "signal-quality-driven brightness, perceptually distinct patterns, and "
    "well-designed error recovery (Figure 4) constitute a coherent interactive "
    "system with clear exhibition value. Critical weaknesses -- calibration "
    "feedback opacity, the wearer-as-non-observer paradox, discrete emotion "
    "classification, instantaneous pattern transitions, and dashboard information "
    "overload -- reduce experiential authenticity and limit usability under "
    "real-world deployment conditions.")

add_body(doc,
    "Future iterations should prioritise: (1) pattern morphing interpolation to "
    "smooth emotional transitions; (2) a secondary display or spatial audio "
    "feedback channel oriented towards the wearer; (3) replacement of the discrete "
    "five-emotion taxonomy with a continuous valence-arousal dimensional model; "
    "and (4) a user-adaptive machine-learning classifier to address individual EEG "
    "variability. These developments would move Sentio from a technically "
    "accomplished demonstrator towards a genuinely personalised and robust "
    "human-machine emotional communication system.")

add_separator(doc)

# Word count
p = doc.add_paragraph()
p.paragraph_format.space_after = Pt(16)
r = p.add_run("Word count: approximately 870 words (body text, excluding captions and references).")
set_font(r, size=10, italic=True, color=(130, 130, 130))
p.alignment = WD_ALIGN_PARAGRAPH.RIGHT

# ── References ────────────────────────────────────────────────────────────────
add_heading(doc, "References")

refs = [
    "Engestrom, Y. (1987). Learning by Expanding: An Activity-Theoretical Approach "
    "to Developmental Research. Orienta-Konsultit.",

    "Hutchins, E. (1995). Cognition in the Wild. MIT Press.",

    "Kaya, N., & Epps, H. H. (2004). Relationship between colour and emotion: "
    "A study of college students. College Student Journal, 38(3), 396-405.",

    "Nielsen, J. (1994). Usability Engineering. Academic Press.",

    "Norman, D. A. (2013). The Design of Everyday Things (Revised ed.). Basic Books.",

    "Wickens, C. D., Lee, J. D., Liu, Y., & Gordon-Becker, S. (2004). "
    "An Introduction to Human Factors Engineering (2nd ed.). Pearson Prentice Hall.",
]

for ref in refs:
    add_ref(doc, ref)

# ── Save ──────────────────────────────────────────────────────────────────────
doc.save(OUT_FILE)
print("Saved -> " + OUT_FILE)

# ── Missing screenshots report ────────────────────────────────────────────────
missing = [f for f, _ in SCREENSHOTS if not os.path.exists(os.path.join(SHOTS_DIR, f))]
if missing:
    print("\nMissing screenshots (save to docs/screenshots/):")
    for f in missing:
        print("  " + f)
else:
    print("All screenshots found and embedded.")
